/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PapayaProfile__factory } from "./PapayaProfile__factory";
export { PapayaStorage__factory } from "./PapayaStorage__factory";
