/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PapayaStorage } from "./PapayaStorage";
export * as factories from "./factories";
export { PapayaStorage__factory } from "./factories/PapayaStorage__factory";
